# src/utils/config.py

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2] # PROJECT PATHS

DATA_DIR = BASE_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
METADATA_DIR = DATA_DIR / "metadata"

# DATASET CONFIGURATION
NUM_CUSTOMERS = 5000
NUM_MERCHANTS = 2000
NUM_TRANSACTIONS = 100_000
FRAUD_RATE = 0.02

SIMULATION_DAYS = 90
START_DATE = "2025-01-01"

# GEOGRAPHY CONFIGURATION
SUBURB_RADIUS_KM_MIN = 5
SUBURB_RADIUS_KM_MAX = 10

CARD_CLONING_DISTANCE_KM = 160
CARD_CLONING_TIME_MINUTES = 60


RANDOM_SEED = 42 # For reproducibility
